### ISSUE TITLE
Add support for "https:/ / youtu.be/XXXXXXXX" links

### ISSUE THREAD

**Issue by CharlesChiuGit** [yoyurec/logseq-awesome-links#25]
**Idea**
Currently only "https:/ / www.youtube.com/watch?v=XXXXXXXX" will show the favicon. But since youtube natively support "https:/ / youtu.be/XXXXX" format, it would nice if it can also have yt favicon in front.

**Screenshots**
![圖片](https://user-images.githubusercontent.com/32497323/207875733-ccf9c956-e630-4918-b150-3dcc72321fc6.png)

Temperately, I use below code to show the favicon, but it will show two favicons.
```css
.external-link[href*="youtu.be"]::before {
  content: "";
  background: url(https://youtube.com/favicon.ico) no-repeat left center;
  background-size: 16px 16px;
  padding-left: 16px;
  margin-right: 4px;
}
```
**Screenshots**
![圖片](https://user-images.githubusercontent.com/32497323/207876701-cb8ab45b-536d-4937-adf5-8cada176a2aa.png)
