### ISSUE TITLE
Setting icon-set doesn't reflect on textarea in editing mode

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-awesome-links#48]
**Info:**
- OS: MacOS 12.6
- Logseq ver: 0.9.4
- Plugin ver: 1.15.16
- Theme name: Default Light

* [x] ⚠ Do i have issue with DISABLED my `custom.css`?

# Description
Setting icon-set doesn't reflect on textarea in editing mode. Expected to change styles for text area with changing this setting.

## ✅ With tabler icons:
<img width="400px" src="https://user-images.githubusercontent.com/1984175/234565390-d2df3a9b-5f6a-4744-93b9-5d590ab8bcf9.png"/>

## 🚫 With nerd font:
<img width="400px" src="https://user-images.githubusercontent.com/1984175/234565413-4b975279-d04e-4bc4-a1f0-33d5e3572b06.png"/>

**Comment by ArnaudCHEVALME** [comment]
I have the same issue. Did you ever find a fix @stdword ?

**Comment by stdword** [comment]
@ArnaudCHEVALME, yep

<img width="200px" src="https://github.com/user-attachments/assets/622a52c8-8d70-4c37-aafc-a7064a7d232d"/>

Try this CSS:
```css
body[data-awli-icon-font=nerd] .editor-inner textarea {
    font-family: var(--ls-font-family),"nerd","tabler-icons",sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol!important;
}
```

It is suitable for MacOS. For other OS you need to adapt it. But the focus should be on `"nerd"` front right after the `var(--ls-font-family)`.
